[[packages]]
typ = "app"
name = "memtest-x86_64"
version = "Null"
description = "memtest runs on x86_64-qemu-q35"

[[packages]]
typ = "app"
name = "memtest-aarch64"
version = "Null"
description = "memtest runs on aarch64-qemu-virt"